# in your Dockerfile
#FROM sphinxdoc/sphinx as build
FROM sphinxdoc/sphinx-latexpdf:7.1.2

WORKDIR /src
COPY src/ ./src/
COPY requirements.txt .
copy *.readthedocs.yaml .
COPY Makefile .
RUN pip3 install -r requirements.txt
RUN ls -l
RUN make html